import React from "react";



const Terms = () => {
  return (
    <>
    <div>
        <br /> Terms and conditions <br />
        <br />1. You agree that you own all the intellectual property and/or the copyright of all the material you upload to DocDome. <br />
        <br />2. DocDome reserves the right to investigate any intellectual property and/or copyright infringements claims. <br />
        <br />3. Valid intellectual property and copyright claims, as determined by DocDome in accordance with applicable legal laws will entitle DocDome to remove the affected material from its platform and you forfeit to receive any associated payments that may have been generated by the affected material.  <br /> 
        <br />4. DocDome will not be compelled to do any payments whatsoever to any person(s) in connection to the unlawfully uploading of material to its platform.  <br />
        <br />5. You acknowledge and accept that DocDome is not involved in the manufacturing of the material you upload to the platform.  As such, DocDome cannot guarantee the correctness of the material uploaded on its platform.  <br />
        <br />6. You agree that the material you upload to DocDome will not infringe or violate a third party’s intellectual property rights or copyright.<br />
        <br />7. You cede the right to delete your material once another user has purchased it. <br />
        <br />8. DocDome reserves the right to amend the tariffs of the rendered services i.e. the service fees and the transaction costs. <br />
        <br />9. DocDome reserves the right to make technical and procedural changes, including web contents, to the platform, in the event it deems utterly necessary solely to its discretion, without being liable to you. <br />
        <br />10. If you leave your wallet unclaimed for three or more consecutive months (after having reached the minimum claimable amount), an administrative fee will be charged. <br />
        <br />11. DocDome is entitled to charge an administrative fee of R9 on a monthly basis, effective on the 93rd day your wallet is not claimed upon becoming claimable. A notice will be sent to the user’s email a month prior the fee become chargeable. <br />
        <br />12. DocDome does not guarantee that the platform will always be available or accessible at all times without any form of disturbance(s) and/or limitations. There may be disruptions due to updates. <br />
     </div>
     <div>
        <p>If you have any questions, you can contact us</p>
     </div>
    </>
  )
}

export default Terms